heat_template_version: 2014-10-16

description: |
  Setup instance for developing chef hook

resources:

  server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: stack-test-server
          params:
            stack: { get_param: "OS::stack_name" }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
      image: c403d8f9-1865-4bf1-9897-ef4e62565c36 # Ubuntu 14.04 with agents
      flavor: 2 GB Performance
      config_drive: true
      software_config_transport: POLL_TEMP_URL
      user_data_format: SOFTWARE_CONFIG

  redis_password:
    type: OS::Heat::RandomString
    properties:
      length: 16
      sequence: lettersdigits

  redis_config:
   type: OS::Heat::SoftwareConfig
   properties:
     group: chef
     inputs:
     - name: redisio
       type: Json
     config: |
       ["recipe[apt]",
        "recipe[build-essential]",
        "recipe[redisio::default]",
        "recipe[redisio::enable]" ]
     options:
       kitchen: https://github.com/rackspace-orchestration-templates/redis-single

  deploy_redis:
   type: OS::Heat::SoftwareDeployment
   properties:
     signal_transport: TEMP_URL_SIGNAL
     input_values:
       redisio:
         default_settings:
           requirepass: { get_attr: [redis_password, value] }
         servers:
         - name:
             str_replace:
               template: stack-test-server
               params:
                 stack: { get_param: "OS::stack_name" }
           port: 6379
         version: "2.8.14"
     config:
       get_resource: redis_config
     server:
       get_resource: server
