heat_template_version: 2015-10-15

description: |
 #### Drupal, Multiple Servers

parameter_groups:
- label: Drupal Settings
  parameters:
  - drupal_url
  - drupal_sitename
  - drupal_user
  - drupal_email

parameters:
  #Drupal Customization
  drupal_url:
    type: string
    default: example.com
    label: Site Domain
    description: Domain to use with Drupal Site
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9.-]{1,255}.[a-zA-Z]{2,15}$"
      description: Must be a valid domain name
  drupal_sitename:
    type: string
    default: Example Site
    label: Site Title
    description: Title to use for Drupal Site
  drupal_user:
    type: string
    default: admin
    label: Drupal Admin Username
    description: Username for Drupal login
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9]*$"
      description: Only can contain A-Z and 0-9
  drupal_email:
    type: string
    default: admin@example.com
    label: Drupal Admin E-mail
    description: E-mail Address for Drupal Admin User
  #Advanced Options
  server_flavor:
    type: string
    default: 4 GB General Purpose v1
    constraints:
    - allowed_values:
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
  server_image:
    type: string
    default: Red Hat Enterprise Linux 7 (PVHVM)
    constraints:
    - allowed_values:
      - Red Hat Enterprise Linux 7 (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
  server_count:
    type: number
    default: 1
    constraints:
      - range: { min: 0, max: 10 }
  child_template:
    type: string
    default: https://raw.githubusercontent.com/chrishultin/ansible-templates/master/Drupal-Multi-Slave.yaml

resources:
  #Passwords
  mysql_root_pw:
    type: OS::Heat::RandomString
  drupal_pass:
    type: OS::Heat::RandomString
  database_pass:
    type: OS::Heat::RandomString
  holland_pass:
    type: OS::Heat::RandomString
  #SSH Key
  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true
  #Cloud Database
  drupal_database:
    type: OS::Trove::Instance
    properties:
      name:
        str_replace:
          template: stack_Database
          params:
            stack: { get_param: "OS::stack_name" }
      flavor: 1GB Instance
      size: 5
      datastore_type: mysql
      datastore_version: "5.6"
      databases:
      - name: drupal
      users:
      - name: drupal
        password: { get_attr: [database_pass, value] }
        databases: [drupal]
      - name: holland
        password: { get_attr: [holland_pass, value] }
        databases: [drupal]
  #Software Configurations
  upload_role_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      outputs:
      - name: results
      config: |
        #!/bin/bash
        set -e
        git clone --progress https://github.com/chrishultin/ansible-roles.git /etc/ansible/roles > $heat_outputs_path.results 2>&1
  drupal_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config: |
        ---
        - name: Install and configure Drupal
          hosts: localhost
          connection: local
          roles:
          - common
          - apache
          - php
          - holland
          - composer
          - drupal
          - firewall
          - lsync
          - phpmyadmin
  deploy_roles:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: upload_role_config
      server:
        get_resource: drupal_server
  deploy_drupal:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_roles
    properties:
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        apache_default_domain: { get_param: drupal_url }
        tz: "America/Chicago"
        holland_mysql_user: "holland"
        holland_mysql_password: {  get_attr: [holland_pass, value] }
        holland_mysql_host: { get_attr: [drupal_database, hostname] }
        holland_create_user: "no"
        drupal_db_host: { get_attr: [drupal_database, hostname] }
        drupal_db_name: "drupal"
        drupal_db_user: "drupal"
        drupal_db_pass: { get_attr: [database_pass, value] }
        drupal_domain: { get_param: drupal_url }
        drupal_user: { get_param: drupal_user }
        drupal_pass: { get_attr: [drupal_pass, value] }
        lsync_private_key: { get_attr: [ssh_key, private_key] }
        lsync_servers_str: { get_attr: [drupal_secondary, private_ip] }
        firewall_global_rules: [ "0.0.0.0,0,22,tcp", "0.0.0.0,0,80,tcp", "0.0.0.0,0,443,tcp"]
        firewall_nodes: { get_attr: [drupal_secondary, private_ip] }
        firewall_node_rules: []
        phpmyadmin_host: { get_attr: [drupal_database, hostname] }
      config:
        get_resource: drupal_config
      server:
        get_resource: drupal_server
  bootstrap:
    type: "https://raw.githubusercontent.com/rackspace-orchestration-templates/software-config-bootstrap/master/bootconfig_yum_ansible.yaml"
  #Master Server
  drupal_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: "OS::stack_name" }
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      key_name: { get_resource: ssh_key }
      software_config_transport: POLL_TEMP_URL
      config_drive: true
      user_data_format: SOFTWARE_CONFIG
      user_data: { get_attr: [ bootstrap, config ] }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        build_config: "backup_agent_only,monitoring_defaults"
  #Monitoring Checks
  drupal_server_http_check:
    type: Rackspace::CloudMonitoring::Check
    depends_on: deploy_drupal
    properties:
      entity: { get_resource: drupal_server }
      type: remote.http
      label:
        str_replace:
          template: stack Master HTTP Check
          params:
            stack: { get_param: "OS::stack_name" }
      details:
        url:
          str_replace:
            template: "http://ipaddr"
            params:
              ipaddr: { get_attr: [drupal_server, accessIPv4] }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      period: 120
      timeout: 10
      monitoring_zones_poll:
      - Northern Virginia (IAD)
      - Chicago (ORD)
      - Dallas Fort Worth (DFW)
      - London (LON)
      target_hostname: { get_attr: [drupal_server, accessIPv4] }
      target_receiver: IPv4
  load_balancer_http_check:
    type: Rackspace::CloudMonitoring::Check
    depends_on: load_balancer
    properties:
      entity: { get_resource: drupal_server }
      type: remote.http
      label:
        str_replace:
          template: stack Load Balancer HTTP Check
          params:
            stack: { get_param: "OS::stack_name" }
      details:
        url:
          str_replace:
            template: "http://ipaddr"
            params:
              ipaddr: { get_attr: [load_balancer, PublicIp] }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      period: 120
      timeout: 10
      monitoring_zones_poll:
      - Northern Virginia (IAD)
      - Chicago (ORD)
      - Dallas Fort Worth (DFW)
      - London (LON)
      target_hostname: { get_attr: [load_balancer, PublicIp] }
      target_receiver: IPv4
  #Cloud Backup
  drupal_backup:
    type: Rackspace::Cloud::BackupConfig
    depends_on: drupal_server
    properties:
      host_ip_address: { get_attr: [drupal_server, accessIPv4] }
      BackupConfigurationName:
        str_replace:
          template: stack Weekly Backup
          params:
            stack: { get_param: "OS::stack_name" }
      Inclusions:
      - FilePath: "/var/spool/holland"
        FileItemType: "Folder"
      - FilePath: "/var/www/"
        FileItemType: "Folder"
      NotifyFailure: true
      NotifyRecipients: { get_param: drupal_email }
      TimeZoneId: Central Standard Time
      StartTimeAmPm: AM
      StartTimeHour: 1
      StartTimeMinute: 0
      HourInterval: null
      DayOfWeekId: 0
      Frequency: "Weekly"
      VersionRetention: 30
  #Secondary Server
  drupal_secondary:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: server_count }
      resource_def:
        type: { get_param: child_template }
        properties:
          ssh_key: { get_resource: ssh_key }
          parent_stack_id: { get_param: "OS::stack_id" }
          server_image: { get_param: server_image }
          server_flavor: { get_param: server_flavor }
          apache_default_domain: { get_param: drupal_url }
          server_name:
            str_replace:
              template: stack-secondary-%index%
              params:
                stack: { get_param: "OS::stack_name" }
  #Cloud Load Balancer
  load_balancer:
    type: Rackspace::Cloud::LoadBalancer
    depends_on:
    - deploy_drupal
    - drupal_secondary
    properties:
      name:
        str_replace:
          template: stack_Load_Balancer
          params:
            stack: { get_param: "OS::stack_name" }
      nodes:
      - addresses: [ { get_attr: [drupal_server, networks, private, 0] } ]
        port: 80
        condition: ENABLED
      - addresses: { get_attr: [drupal_secondary, private_ip] }
        port: 80
        condition: ENABLED
      port: 80
      protocol: HTTP
      algorithm: ROUND_ROBIN
      contentCaching: ENABLED
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4
      metadata:
        rax-heat: { get_param: "OS::stack_id" }

outputs:
  drupal_login_user:
    description: WordPress Admin User
    value:
      get_param: drupal_user
  drupal_login_password:
    description: WordPress Admin Password
    value:
      get_attr: [drupal_pass, value]
  drupal_public_ip:
    description: Load Balancer IP
    value:
      get_attr: [load_balancer, PublicIp]
  drupal_admin_url:
    description: WordPress Admin URL
    value:
      str_replace:
        template: "https://domain/wp-admin/"
        params:
          domain: { get_param: drupal_url }
  drupal_public_url:
    description: WordPress Public URL
    value:
      str_replace:
        template: "http://domain/"
        params:
          domain: { get_param: drupal_url }
  phpmyadmin_url:
    description: PHPMyAdmin URL
    value:
      str_replace:
        template: "https://IP/phpmyadmin/"
        params:
          IP:
            get_attr: [drupal_server, accessIPv4]
  mysql_user:
    description: Database User
    value: "drupal"
  mysql_password:
    description: Database Password
    value:
      get_attr: [database_pass, value]
  ssh_private_key:
    description: SSH Private Key
    value:
      get_attr: [ssh_key, private_key]
  server_ip:
    description: Server Public IP
    value:
      get_attr: [drupal_server, accessIPv4]
  secondary_ips:
    description: Secondary Node IPs
    value:
      get_attr: [drupal_secondary, public_ip]
