heat_template_version: 2015-10-15

description: |
 #### Reference Architecture, Secondary

parameter_groups:

parameters:
  server_name:
    type: string
    default: example-0
  server_flavor:
    type: string
    default: 1 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
  server_image:
    type: string
    default: f4bbbce2-50b0-4b07-bf09-96c175a45f4b
    constraints:
    - allowed_values:
      - f4bbbce2-50b0-4b07-bf09-96c175a45f4b
  ssh_key:
    type: string
    label: SSH Key
    description: SSH Key for Secondary Nodes
  parent_stack_id:
    type: string
    default: None
  apache_default_domain:
    type: string
    default: example.com
  master_server:
    type: string
resources:
  upload_role_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      outputs:
      - name: results
      config: |
        #!/bin/bash
        set -e
        git clone -b 'stable' --single-branch --progress https://github.com/rackspace-orchestration-templates/ansible-roles.git /etc/ansible/roles > $heat_outputs_path.results 2>&1

  apache_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config: |
        ---
        - name: Install and configure Apache and Firewall
          hosts: localhost
          connection: local
          roles:
          - common
          - apache
          - firewall
  deploy_roles:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: upload_role_config
      server:
        get_resource: secondary_server
  deploy_apache:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_roles
    properties:
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        nginx_vhost_str: { get_param: apache_default_domain }
        nginx_vhost_template: 'default_secondary'
        nginx_upstream_server: { get_param: master_server }
        tz: "America/Chicago"
      config:
        get_resource: apache_config
      server:
        get_resource: secondary_server
  secondary_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: "server_name" }
      key_name: { get_param: "ssh_key" }
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      software_config_transport: POLL_TEMP_URL
      config_drive: true
      user_data_format: SOFTWARE_CONFIG
      metadata:
        rax-heat: { get_param: "parent_stack_id" }
        build_config: "monitoring_defaults"

outputs:
  public_ip:
    description: Server Public IP
    value:
      get_attr: [secondary_server, accessIPv4]
  private_ip:
    description: Server Private IP
    value:
      get_attr: [secondary_server, networks, private, 0]
