heat_template_version: 2015-10-15

description: Software Config Bootstrap

parameter_groups:

parameters:

resources:
  boostrap_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: "OS::stack_name" }
      image: dc3ff0d8-f0d0-4b2c-b105-ffe421fec277
      flavor: 2 GB Performance
      software_config_transport: POLL_TEMP_URL
      config_drive: true
      user_data_format: SOFTWARE_CONFIG
